# Generated by Django 4.0.2 on 2022-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-12-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='time',
            field=models.TimeField(auto_now_add=True, default='18:43'),
            preserve_default=False,
        ),
    ]
