# Generated by Django 4.0.2 on 2022-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_gallery_date_gallery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(max_length=200, upload_to='images'),
        ),
    ]
