# Generated by Django 4.0.2 on 2022-12-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0005_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('time',)},
        ),
    ]
