# Generated by Django 4.0.2 on 2022-12-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0006_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
    ]
