# Generated by Django 4.0.2 on 2022-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0007_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='Galleries'),
        ),
    ]
